Import('env', 'envCython', 'arch')

# params.cc is compiled at -O1 on purpose. params_keys.h is a ~500-entry static
# unordered_map that clang constant-folds at -O2, peaking over 2.3GB RSS - more
# than a comma 3X has free. When that OOMs, system/manager/build.py retries the
# *entire* build at -j4 and then -j1, so one file turns a few-minute rebuild into
# an hour. It is a lookup table; there is no hot path to lose here.
_params = env.Object('params', 'params.cc', CCFLAGS=env['CCFLAGS'] + ['-O1'])

common_libs = [
  _params,
  'swaglog.cc',
  'util.cc',
  'watchdog.cc',
  'ratekeeper.cc'
]

_common = env.Library('common', common_libs, LIBS="json11")

files = [
  'clutil.cc',
]

_gpucommon = env.Library('gpucommon', files)
Export('_common', '_gpucommon')

if GetOption('extras'):
  env.Program('tests/test_common',
              ['tests/test_runner.cc', 'tests/test_params.cc', 'tests/test_util.cc', 'tests/test_swaglog.cc'],
              LIBS=[_common, 'json11', 'zmq', 'pthread'])

# Cython bindings
params_python = envCython.Program('params_pyx.so', 'params_pyx.pyx', LIBS=envCython['LIBS'] + [_common, 'zmq', 'json11'])

SConscript([
  'transformations/SConscript',
])

Import('transformations_python')
common_python = [params_python, transformations_python]

Export('common_python')
